#Bring in functions
source ./_vault.functions.inc.bash

# Basic sanity checks
if ! command -v ansible-vault &>/dev/null; then
  echo "Ansible has not been installed - please install ansible before running any of these scripts"
  exit 1
fi

ansibleVersionAtLeast "2.9.9"

readonly environmentPath="$projectDir/environment/"

export environmentArray
readarray -t \
  environmentArray <<<"$(find "$environmentPath" -maxdepth 1 -mindepth 1 -type d -exec basename {} \;)"

# If outputToFile is defined, check for environment in the path
if [[ -n "${outputToFile:-}" ]]; then
  # Capture output in a variable
  finalSpecifiedEnv="$(detectEnvironmentFromPath "$outputToFile" "$specifiedEnv")"
  # Ensure we got a clean value (just the environment name)
  if [[ ! "$finalSpecifiedEnv" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    # If there was extra output, try to extract just the last line
    finalSpecifiedEnv="$(echo "$finalSpecifiedEnv" | tail -n1)"
  fi
else
  finalSpecifiedEnv="$specifiedEnv"
fi

assertValidEnv "$finalSpecifiedEnv"

readonly vaultSecretsPath="$projectDir/vault-pass-${finalSpecifiedEnv}.secret"

if [[ ! -f $vaultSecretsPath ]]; then
  echo "Vault Pass File not found at $vaultSecretsPath, you need to create this first"
  exit 1
fi

# Refuse an over-permissive passphrase file, the way ssh refuses a private key
# that others can read. This is the one file that decrypts every secret in the
# project, so it is worth being as blunt about as ssh is.
#
# The check is here rather than in the script that creates the file because
# creation is not the only way to get a bad mode: a file generated by a version
# of generateVaultSecret.bash from before it chmod'ed, one restored from a
# backup or copied between machines, or one loosened later, all arrive here.
# Every script that can read the passphrase sources this file, so this is the
# single place that sees all of them.
#
# Deliberately NOT auto-fixed. A silent chmod would hide the real question —
# who could already read it — and make an exposure look like a non-event.
vaultSecretsMode="$(stat -c '%a' "$vaultSecretsPath")"
if ((8#$vaultSecretsMode & 8#077)); then
  cat >&2 <<ERRMSG

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: UNPROTECTED VAULT PASSPHRASE FILE!           @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Permissions $vaultSecretsMode for '$vaultSecretsPath' are too open.
It is required that your vault passphrase file is NOT accessible by others.

This file decrypts every secret in this project. Any user with a shell on
this machine can currently read it.

Fix with:

    chmod 600 $vaultSecretsPath

Then consider the passphrase compromised and rekey if this machine is shared:

    ./rekeyVaultFile.bash

ERRMSG
  exit 1
fi


