- name: Parse Vault Variables
  shell: |
    grep -rhPo '^[^:]+(?=: )' {{env_dir}} | grep '^vault' --color=never
  register: vaultvars
  delegate_to: localhost
  become: false

- name: Debug vaultvars
  debug:
    var: vaultvars

- name: Dump Vault Variables
  debug:
    msg: |

      ---------

      {{ item }}: {{ lookup('vars', item) }}

      ---------
  with_items: "{{ vaultvars.stdout_lines }}"