- name: Parse Group Vars Vault Variables
  shell: |
    grep -rhPo '^[^:]+(?=: )' {{env_dir}}/group_vars | grep '^vault' --color=never
  register: vault_group_vars
  delegate_to: localhost
  become: false

- name: Debug vault_group_vars
  debug:
    var: vault_group_vars

- name: Dump Vault Group Vars
  debug:
    msg: |

      ---------

      {{ item }}: {{ lookup('vars', item) }}

      ---------
  with_items: "{{ vault_group_vars.stdout_lines }}"
