---
- name: Dump Group Vars Secrets
  when: single_variable is undefined
  import_tasks: dump-group-vars-secrets.yml
  tags: dump-secrets

- name: Dump Host Vars Secrets
  when: single_variable is undefined
  import_tasks: dump-host-vars-secrets.yml
  tags: dump-secrets

- name: Dump single secret
  when: single_variable is defined
  tags: dump-secrets
  debug:
    msg: "{{ lookup('vars', single_variable) }}"
